export const fallbackProducts = [
  {
    id: "fallback-top-1",
    productName: "Rose Everyday Top",
    brand: "Phalls Attair",
    seller: "Phalls Attair",
    description: "Soft daily-wear top with a polished feminine silhouette.",
    category: "Women's Tops",
    price: 1299,
    productImage: "",
    localImage: "/CordSet1 (3).jpeg",
  },
  {
    id: "fallback-suit-1",
    productName: "Festive Churidar Set",
    brand: "Phalls Attair",
    seller: "Phalls Attair",
    description: "Elegant churidar suit set for festive and occasion dressing.",
    category: "Exquisite Churidar Suits",
    price: 2499,
    productImage: "",
    localImage: "/CordSet1 (10).jpeg",
  },
  {
    id: "fallback-coord-1",
    productName: "Blush Co-Ord Edit",
    brand: "Phalls Attair",
    seller: "Phalls Attair",
    description: "Comfortable co-ord set made for quick styling.",
    category: "Premium Co-Ord Sets",
    price: 1899,
    productImage: "",
    localImage: "/CordSet02.jpeg",
  },
  {
    id: "fallback-gown-1",
    productName: "Evening Designer Gown",
    brand: "Phalls Attair",
    seller: "Phalls Attair",
    description: "Statement gown for premium evening occasions.",
    category: "Designer Gowns",
    price: 3599,
    productImage: "",
    localImage: "/CordSet1 (20).jpeg",
  },
  {
    id: "fallback-kurta-1",
    productName: "Kurta Pant Dupatta Classic",
    brand: "Phalls Attair",
    seller: "Phalls Attair",
    description: "Graceful ethnic set with kurta, pant, and dupatta.",
    category: "Kurta Pant Dupatta Sets",
    price: 2199,
    productImage: "",
    localImage: "/CordSet1 (24).jpeg",
  },
  {
    id: "fallback-night-1",
    productName: "Cotton Nightwear Set",
    brand: "Phalls Attair",
    seller: "Phalls Attair",
    description: "Breathable cotton nightwear made for comfort.",
    category: "Pure Cotton Nightwear",
    price: 999,
    productImage: "",
    localImage: "/CordSet1 (29).jpeg",
  },
  {
    id: "fallback-saree-1",
    productName: "Signature Designer Saree",
    brand: "Phalls Attair",
    seller: "Phalls Attair",
    description: "Elegant saree crafted for premium celebrations.",
    category: "Designer Sarees",
    price: 2899,
    productImage: "",
    localImage: "/CordSet1 (30).jpeg",
  },
  {
    id: "fallback-legging-1",
    productName: "Signature Stretch Leggings",
    brand: "Phalls Attair",
    seller: "Phalls Attair",
    description: "Everyday leggings with a flexible flattering fit.",
    category: "Signature Leggings",
    price: 699,
    productImage: "",
    localImage: "/CordSet1 (32).jpeg",
  },
];
